---
title: "Simple Example"
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simple Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette produces the example shown in figure 1 in section 1.3 of "Rank conditional coverage and confidence intervals in high dimensional problems."

The builtin data set `DELTA` is a 1000 by 4 matrix containing four sets of parameter values. The function `example_sim` simulates normally distributed data from a given vector of means and constructs confidence intervals using the five methods described in the paper 
  - naive
  -oracle rank conditional pivotal intervals
  -parametric bootstrap intervals
  -selection adjusted intervals described by Weinstein et al (2013)
  -sliding thershold variation of the Weinstein et al intervals

The following prduces the simulations shown:
```{r, eval=FALSE}
set.seed(6587900)
sim.list <- list()
for(i in 1:4){
  sim.list[[i]] <- example_sim(DELTA[,i], n=200, use.abs=FALSE)
}
```

## Plotting
To create the 

## A note about absolute value
The functions accompanying  "Selection Adjusted Confidence Intervals with More Power to Determine the Sign" By Asaf Weinstein, William Fithian, and Yoav Benjamini JASA (2012) adjust for selection based on a threshold on the absolute value of the estimate. Bootstrap intervals can be constructed ranking by signed or by absolute value -- algorithms are only given explicitly for signed ranking so this is used in the example. To construct intervals which rank based on absolute value set \code{use.abs=TRUE}
